name: CD [PROD] Next.js

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install NPM Deps (ci)
        run: npm ci

      - name: Build Next.js
        run: |
          npx next telemetry disable
          npm run build

      - name: Start Next.js
        run: |
          pm2 reload all --update-env
