name: Next.js CD

concurrency:
    group: production
    cancel-in-progress: true

on:
    push:
        branches:
            - main
        paths-ignore:
            - '.github/**'
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: self-hosted
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js (22.x)
              uses: actions/setup-node@v4

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: |
                  npx next telemetry disable
                  npm run build
              env:
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

            - name: Reload PM2
              run: pm2 reload all
