name: Next.js CD

concurrency:
    group: production
    cancel-in-progress: true

on:
    push:
        branches:
            - main
        paths-ignore:
            - '.github/**'
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: self-hosted
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js (22.x)
              uses: actions/setup-node@v4
            - name: Install Dependencies
              run: npm ci
            - name: Build
              env:
                  NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: ${{ secrets.NEXT_PUBLIC_TELEGRAM_BOT_TOKEN }}
                  NEXT_PUBLIC_TELEGRAM_CHAT_ID: ${{ secrets.NEXT_PUBLIC_TELEGRAM_CHAT_ID }}
              run: |
                  npx next telemetry disable
                  pm2 stop all
                  rm -rf .next
                  npm run build
                  pm2 restart all
